# Generated by Django 4.0.5 on 2022-06-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='show_in_listings',
            field=models.BooleanField(default=True),
        ),
    ]
