# Generated by Django 4.0.5 on 2022-06-05 08:07

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import utils.times


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpostpage_show_in_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='post_text_for_facebook',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='post_text_for_instagram',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='post_text_for_linkedin',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='post_text_for_telegram',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='post_text_for_twitter',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='promote_in_facebook',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='promote_in_instagram',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='promote_in_linkedin',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='promote_in_telegram',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='promote_in_twitter',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='promoting_time',
            field=models.DateTimeField(blank=True, default=utils.times.one_hour_from_now, null=True, validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.now)]),
        ),
    ]
