# Generated by Django 4.0.5 on 2022-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpostpage_post_text_for_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='share_in_excel_accounts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='share_in_matlab_accounts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='share_in_webdev_accounts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
