# Generated by Django 4.0.5 on 2022-06-05 10:00

from django.db import migrations, models
import utils.times


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpostpage_share_in_excel_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='promoting_time',
            field=models.DateTimeField(default=utils.times.one_hour_from_now, null=True),
        ),
    ]
