# Generated by Django 4.0.5 on 2022-06-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpostpage_promoting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='promoting_time',
        ),
    ]
