# Generated by Django 4.0.5 on 2022-06-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpostpage_promoting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='post_text_for_facebook',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='post_text_for_instagram',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='promote_in_facebook',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='promote_in_instagram',
        ),
    ]
