# Generated by Django 4.0.5 on 2022-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogpostpage_post_text_for_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='create_pdf',
            field=models.BooleanField(default=True),
        ),
    ]
