# Generated by Django 4.0.5 on 2022-06-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('blog', '0008_blogpostpage_create_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
