# Generated by Django 4.0.5 on 2022-06-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpostpage_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='create_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
