# Generated by Django 4.0.5 on 2022-06-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homepage_banner_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sub_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
