# Generated by Django 4.0.5 on 2022-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
